"""Documentation generation from repository structure."""

from __future__ import annotations

from pathlib import Path

from sonec.analysis.architecture import ArchitectureAnalyzer, report_to_mermaid
from sonec.core.workspace import Workspace
from sonec.indexing.index import RepositoryIndex


class DocGenerator:
    def __init__(self, workspace: Workspace) -> None:
        self.workspace = workspace

    def generate_overview(self) -> str:
        index = RepositoryIndex(self.workspace)
        index.build()
        summary = index.summary()
        arch = ArchitectureAnalyzer(self.workspace).analyze("src" if (self.workspace.root / "src").exists() else ".")
        lines = [
            f"# {self.workspace.root.name}",
            "",
            "## Overview",
            "",
            f"Generated by SONEC for `{self.workspace.root}`.",
            "",
            f"- Indexed files: **{summary['file_count']}**",
            f"- Languages: {', '.join(f'{k} ({v})' for k, v in sorted(summary['languages'].items())) or 'n/a'}",
            "",
            "## Module dependency graph",
            "",
            "```mermaid",
            report_to_mermaid(arch),
            "```",
            "",
            "## Top-level layout",
            "",
        ]
        for child in sorted(self.workspace.root.iterdir()):
            if child.name.startswith("."):
                continue
            kind = "dir" if child.is_dir() else "file"
            lines.append(f"- `{child.name}` ({kind})")
        lines.append("")
        return "\n".join(lines)

    def write(self, destination: str | Path = "docs/GENERATED.md") -> Path:
        path = self.workspace.resolve(destination)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.generate_overview(), encoding="utf-8")
        return path
